### PR TITLE
fix: type error due to customTesters in context but not in state

### LINKED ISSUE #9: TypeError: this.customTesters is not iterable in expect.jsonContaining in jest 29.4.0
After upgrading jest to 29.4.0. Using `expect.jsonContaining` triggers the following error `TypeError: this.customTesters is not iterable`.

I suspect this is likely due to changes from https://github.com/facebook/jest/pull/13654.

https://github.com/debugmaster/jest-json-matchers/blob/469552f7dcbcbc78a5dbb91d8dc2cbe0ca986fa9/index.ts#L75 I think that instead of using `expect.getState()` the `this` variable is expected to be passed through.

### PR DESCRIPTION
**Pull request by justin-tay**
Fixes #9

I think this should minimally be compatible from `expect` 27.5.1 which I see is used in `package-lock.json`.

The calling code to the matcher is

```
        asymmetricMatch(other) {
          const {pass} = matcher.call(
            this.getMatcherContext(),
            other,
            ...this.sample
          );
          return this.inverse ? !pass : pass;
        }
```
that is in `jestMatchersObject` in `expect`.

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -71,6 +71,6 @@ export function toMatchJSON(this: MatcherState, received: unknown, jsonObject: a
     return matchers.toMatchObject.call(this, JSON.parse(received as string), jsonObject)
 }
 
-export function jsonContaining(received: unknown, jsonObject: any): ExpectationResult {
-    return toMatchJSON.call(expect.getState() as MatcherState, received, jsonObject)
+export function jsonContaining(this: MatcherState, received: unknown, jsonObject: any): ExpectationResult {
```
Comment (debugmaster) [inline index.ts:74]: This change seems safe, but did you try it against both new and old versions?

Comment (debugmaster) [reply index.ts:74]: I will accept your change. Thanks for looking into it and contributing to the repository.

A lot has changed on the last Jest/Expect versions, so I will take care of upgrading this package to latest. I will release a new version in a couple of hours.

**Review by debugmaster — APPROVED** [review]

**Comment by debugmaster** [comment]
I have upgraded the project to consume Jest 29.4. The mistake is clear in the new types. 

`expect.getState()` returns `MatcherState`, but matchers require `MatcherContext = MatchersState & MatcherUtils` to be fully defined.
